export const USER_LOGIN_FETCHING = 'USER_LOGIN_FETCHING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

export const USER_REGISTER_FETCHING = 'USER_REGISTER_FETCHING'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export const USER_ADDMEMBER_FETCHING = 'USER_ADDMEMBER_FETCHING'
export const USER_ADDMEMBER_SUCCESS = 'USER_ADDMEMBER_SUCCESS'
export const USER_ADDMEMBER_FAILURE = 'USER_ADDMEMBER_FAILURE'

export const USER_GETMEMBERS_FETCHING = 'USER_GETMEMBERS_FETCHING'
export const USER_GETMEMBERS_SUCCESS = 'USER_GETMEMBERS_SUCCESS'
export const USER_GETMEMBERS_FAILURE = 'USER_GETMEMBERS_FAILURE'

export const USER_LOGINMEMBER_FETCHING = 'USER_LOGINMEMBER_FETCHING'
export const USER_LOGINMEMBER_SUCCESS = 'USER_LOGINMEMBER_SUCCESS'
export const USER_LOGINMEMBER_FAILURE = 'USER_LOGINMEMBER_FAILURE'

export const USER_EDITMEMBER_FETCHING = 'USER_EDITMEMBER_FETCHING'
export const USER_EDITMEMBER_SUCCESS = 'USER_EDITMEMBER_SUCCESS'
export const USER_EDITMEMBER_FAILURE = 'USER_EDITMEMBER_FAILURE'

export const USER_DELETE_FETCHING = 'USER_DELETE_FETCHING'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE'


export const APIS_GET_FETCHING = 'APIS_GET_FETCHING'
export const APIS_GET_SUCCESS = 'APIS_GET_SUCCESS'
export const APIS_GET_FAILURE = 'APIS_GET_FAILURE'
export const APIS_CLEAR = 'APIS_CLEAR'